config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.CourseView.as_view(), name='course-list'),
    path('update/<int:pk>', views.CourseUpdateView.as_view(), name='course-edit'),
    path('create/', views.CourseCreateView.as_view(), name='course-create'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact_message_view, name='contact_message_view'),
]

home/models.py
from django.db import models


class ContactMessage(models.Model):
    fullname = models.CharField(max_length=100)
    email = models.EmailField(max_length=150)
    message = models.TextField()

    def __str__(self):
        return f'{self.fullname}, {self.message[:10]}'

home/forms.py
from django import forms
from . import models


class ContactMessageForm(forms.ModelForm):
    class Meta:
        model = models.ContactMessage
        fields = ('fullname', 'email', 'message')

home/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView

from . import forms


def home(request):
    return render(request, 'home/home.html')


class HomeView(TemplateView):
    template_name = 'home/home.html'


def contact_message_view(request):
    form = forms.ContactMessageForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('home:home')

    return render(request, 'home/contact_message.html', {'form': form})

home/templates/home/contact_message.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Contact
{% endblock %}

{% block container %}
    <form action="" method="post">
        {% csrf_token %}

        {{ form|crispy }}

        <button type="submit" class="btn btn-primary">Send message</button>
    </form>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock %}

{% block container %}
    <h1>LMS - Learning management system</h1>
    <div>
        <a href="{% url 'courses:course-list' %}" class="btn btn-info">Check courses</a>
    </div>
{% endblock %}