config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.CourseView.as_view(), name='course-list'),
    path('update/<int:pk>', views.CourseUpdateView.as_view(), name='course-edit'),
    path('create/', views.CourseCreateView.as_view(), name='course-create'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact_message_view, name='contact_message_view'),
]

courses/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Course(models.Model):
    title = models.CharField(max_length=200)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='courses_creator')

    def __str__(self):
        return self.title

courses/forms.py
from django import forms

from . import models


class CourseForm(forms.ModelForm):
    class Meta:
        model = models.Course
        fields = ('title',)

courses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DetailView

from . import models
from .permissions import AuthorManageMixin


class CourseView(ListView):
    template_name = 'courses/courses_list.html'
    model = models.Course
    context_object_name = 'courses'


class CourseDetailView(DetailView):
    model = models.Course
    context_object_name = 'course'
    template_name = 'courses/course_detail.html'


class CourseCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.Course
    fields = ('title',)
    template_name = 'courses/course_create.html'
    login_url = reverse_lazy('users:login_view')
    success_url = reverse_lazy('courses:course-list')
    permission_required = 'courses.add_course'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class CourseUpdateView(LoginRequiredMixin, AuthorManageMixin, UpdateView):
    model = models.Course
    fields = ('title',)
    template_name = 'courses/course_edit.html'
    success_url = reverse_lazy('courses:course-list')
    context_object_name = 'course'
    login_url = reverse_lazy('users:login_view')

courses/templates/courses/course_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create Course My Lord
{% endblock %}

{% block container %}
    <form action="" method="post">
        {% csrf_token %}
        <h3 class="text-center">Create course</h3>

        {{ form|crispy }}

        <button type="submit" class="btn btn-success float-right btn-lg mb-3 mt-0">Add Course</button>
    </form>
{% endblock %}

courses/templates/courses/course_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Edit Course My Lord
{% endblock %}

{% block container %}
    <form action="" method="post">
        {% csrf_token %}
        <h3 class="text-center">Editing course: {{ course.title }}</h3>

        {{ form|crispy }}

        <button type="submit" class="btn btn-success float-right btn-lg mb-3 mt-0">Update Course</button>
    </form>
{% endblock %}

courses/templates/courses/courses_list.html
{% extends 'base.html' %}

{% block title %}
    Courses List
{% endblock %}

{% block container %}
    <h1>Courses List:</h1>
    <ul>
        {% for course in courses %}
            <li class="mb-3">{{ course.title }} <a href="{% url 'courses:course-edit' pk=course.id %}" class="btn btn-warning btn-sm">Edit</a></li>
        {% empty %}
            <p>Something is no yes :)</p>
        {% endfor %}
    </ul>
{% endblock %}